// <auto-generated />
using Catalog.Persistence.Databese;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.Databese.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210905135056_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Descripcion = "Description for product 1",
                            Name = "Product1",
                            Price = 233m
                        },
                        new
                        {
                            ProductId = 2,
                            Descripcion = "Description for product 2",
                            Name = "Product2",
                            Price = 359m
                        },
                        new
                        {
                            ProductId = 3,
                            Descripcion = "Description for product 3",
                            Name = "Product3",
                            Price = 849m
                        },
                        new
                        {
                            ProductId = 4,
                            Descripcion = "Description for product 4",
                            Name = "Product4",
                            Price = 760m
                        },
                        new
                        {
                            ProductId = 5,
                            Descripcion = "Description for product 5",
                            Name = "Product5",
                            Price = 735m
                        },
                        new
                        {
                            ProductId = 6,
                            Descripcion = "Description for product 6",
                            Name = "Product6",
                            Price = 137m
                        },
                        new
                        {
                            ProductId = 7,
                            Descripcion = "Description for product 7",
                            Name = "Product7",
                            Price = 318m
                        },
                        new
                        {
                            ProductId = 8,
                            Descripcion = "Description for product 8",
                            Name = "Product8",
                            Price = 228m
                        },
                        new
                        {
                            ProductId = 9,
                            Descripcion = "Description for product 9",
                            Name = "Product9",
                            Price = 168m
                        },
                        new
                        {
                            ProductId = 10,
                            Descripcion = "Description for product 10",
                            Name = "Product10",
                            Price = 580m
                        },
                        new
                        {
                            ProductId = 11,
                            Descripcion = "Description for product 11",
                            Name = "Product11",
                            Price = 203m
                        },
                        new
                        {
                            ProductId = 12,
                            Descripcion = "Description for product 12",
                            Name = "Product12",
                            Price = 106m
                        },
                        new
                        {
                            ProductId = 13,
                            Descripcion = "Description for product 13",
                            Name = "Product13",
                            Price = 350m
                        },
                        new
                        {
                            ProductId = 14,
                            Descripcion = "Description for product 14",
                            Name = "Product14",
                            Price = 545m
                        },
                        new
                        {
                            ProductId = 15,
                            Descripcion = "Description for product 15",
                            Name = "Product15",
                            Price = 990m
                        },
                        new
                        {
                            ProductId = 16,
                            Descripcion = "Description for product 16",
                            Name = "Product16",
                            Price = 480m
                        },
                        new
                        {
                            ProductId = 17,
                            Descripcion = "Description for product 17",
                            Name = "Product17",
                            Price = 481m
                        },
                        new
                        {
                            ProductId = 18,
                            Descripcion = "Description for product 18",
                            Name = "Product18",
                            Price = 612m
                        },
                        new
                        {
                            ProductId = 19,
                            Descripcion = "Description for product 19",
                            Name = "Product19",
                            Price = 173m
                        },
                        new
                        {
                            ProductId = 20,
                            Descripcion = "Description for product 20",
                            Name = "Product20",
                            Price = 475m
                        },
                        new
                        {
                            ProductId = 21,
                            Descripcion = "Description for product 21",
                            Name = "Product21",
                            Price = 213m
                        },
                        new
                        {
                            ProductId = 22,
                            Descripcion = "Description for product 22",
                            Name = "Product22",
                            Price = 171m
                        },
                        new
                        {
                            ProductId = 23,
                            Descripcion = "Description for product 23",
                            Name = "Product23",
                            Price = 946m
                        },
                        new
                        {
                            ProductId = 24,
                            Descripcion = "Description for product 24",
                            Name = "Product24",
                            Price = 523m
                        },
                        new
                        {
                            ProductId = 25,
                            Descripcion = "Description for product 25",
                            Name = "Product25",
                            Price = 172m
                        },
                        new
                        {
                            ProductId = 26,
                            Descripcion = "Description for product 26",
                            Name = "Product26",
                            Price = 679m
                        },
                        new
                        {
                            ProductId = 27,
                            Descripcion = "Description for product 27",
                            Name = "Product27",
                            Price = 710m
                        },
                        new
                        {
                            ProductId = 28,
                            Descripcion = "Description for product 28",
                            Name = "Product28",
                            Price = 754m
                        },
                        new
                        {
                            ProductId = 29,
                            Descripcion = "Description for product 29",
                            Name = "Product29",
                            Price = 268m
                        },
                        new
                        {
                            ProductId = 30,
                            Descripcion = "Description for product 30",
                            Name = "Product30",
                            Price = 871m
                        },
                        new
                        {
                            ProductId = 31,
                            Descripcion = "Description for product 31",
                            Name = "Product31",
                            Price = 780m
                        },
                        new
                        {
                            ProductId = 32,
                            Descripcion = "Description for product 32",
                            Name = "Product32",
                            Price = 938m
                        },
                        new
                        {
                            ProductId = 33,
                            Descripcion = "Description for product 33",
                            Name = "Product33",
                            Price = 216m
                        },
                        new
                        {
                            ProductId = 34,
                            Descripcion = "Description for product 34",
                            Name = "Product34",
                            Price = 490m
                        },
                        new
                        {
                            ProductId = 35,
                            Descripcion = "Description for product 35",
                            Name = "Product35",
                            Price = 941m
                        },
                        new
                        {
                            ProductId = 36,
                            Descripcion = "Description for product 36",
                            Name = "Product36",
                            Price = 710m
                        },
                        new
                        {
                            ProductId = 37,
                            Descripcion = "Description for product 37",
                            Name = "Product37",
                            Price = 291m
                        },
                        new
                        {
                            ProductId = 38,
                            Descripcion = "Description for product 38",
                            Name = "Product38",
                            Price = 979m
                        },
                        new
                        {
                            ProductId = 39,
                            Descripcion = "Description for product 39",
                            Name = "Product39",
                            Price = 814m
                        },
                        new
                        {
                            ProductId = 40,
                            Descripcion = "Description for product 40",
                            Name = "Product40",
                            Price = 506m
                        },
                        new
                        {
                            ProductId = 41,
                            Descripcion = "Description for product 41",
                            Name = "Product41",
                            Price = 894m
                        },
                        new
                        {
                            ProductId = 42,
                            Descripcion = "Description for product 42",
                            Name = "Product42",
                            Price = 909m
                        },
                        new
                        {
                            ProductId = 43,
                            Descripcion = "Description for product 43",
                            Name = "Product43",
                            Price = 343m
                        },
                        new
                        {
                            ProductId = 44,
                            Descripcion = "Description for product 44",
                            Name = "Product44",
                            Price = 116m
                        },
                        new
                        {
                            ProductId = 45,
                            Descripcion = "Description for product 45",
                            Name = "Product45",
                            Price = 142m
                        },
                        new
                        {
                            ProductId = 46,
                            Descripcion = "Description for product 46",
                            Name = "Product46",
                            Price = 964m
                        },
                        new
                        {
                            ProductId = 47,
                            Descripcion = "Description for product 47",
                            Name = "Product47",
                            Price = 716m
                        },
                        new
                        {
                            ProductId = 48,
                            Descripcion = "Description for product 48",
                            Name = "Product48",
                            Price = 365m
                        },
                        new
                        {
                            ProductId = 49,
                            Descripcion = "Description for product 49",
                            Name = "Product49",
                            Price = 457m
                        },
                        new
                        {
                            ProductId = 50,
                            Descripcion = "Description for product 50",
                            Name = "Product50",
                            Price = 768m
                        },
                        new
                        {
                            ProductId = 51,
                            Descripcion = "Description for product 51",
                            Name = "Product51",
                            Price = 814m
                        },
                        new
                        {
                            ProductId = 52,
                            Descripcion = "Description for product 52",
                            Name = "Product52",
                            Price = 724m
                        },
                        new
                        {
                            ProductId = 53,
                            Descripcion = "Description for product 53",
                            Name = "Product53",
                            Price = 626m
                        },
                        new
                        {
                            ProductId = 54,
                            Descripcion = "Description for product 54",
                            Name = "Product54",
                            Price = 216m
                        },
                        new
                        {
                            ProductId = 55,
                            Descripcion = "Description for product 55",
                            Name = "Product55",
                            Price = 712m
                        },
                        new
                        {
                            ProductId = 56,
                            Descripcion = "Description for product 56",
                            Name = "Product56",
                            Price = 162m
                        },
                        new
                        {
                            ProductId = 57,
                            Descripcion = "Description for product 57",
                            Name = "Product57",
                            Price = 412m
                        },
                        new
                        {
                            ProductId = 58,
                            Descripcion = "Description for product 58",
                            Name = "Product58",
                            Price = 425m
                        },
                        new
                        {
                            ProductId = 59,
                            Descripcion = "Description for product 59",
                            Name = "Product59",
                            Price = 687m
                        },
                        new
                        {
                            ProductId = 60,
                            Descripcion = "Description for product 60",
                            Name = "Product60",
                            Price = 155m
                        },
                        new
                        {
                            ProductId = 61,
                            Descripcion = "Description for product 61",
                            Name = "Product61",
                            Price = 426m
                        },
                        new
                        {
                            ProductId = 62,
                            Descripcion = "Description for product 62",
                            Name = "Product62",
                            Price = 564m
                        },
                        new
                        {
                            ProductId = 63,
                            Descripcion = "Description for product 63",
                            Name = "Product63",
                            Price = 959m
                        },
                        new
                        {
                            ProductId = 64,
                            Descripcion = "Description for product 64",
                            Name = "Product64",
                            Price = 297m
                        },
                        new
                        {
                            ProductId = 65,
                            Descripcion = "Description for product 65",
                            Name = "Product65",
                            Price = 800m
                        },
                        new
                        {
                            ProductId = 66,
                            Descripcion = "Description for product 66",
                            Name = "Product66",
                            Price = 264m
                        },
                        new
                        {
                            ProductId = 67,
                            Descripcion = "Description for product 67",
                            Name = "Product67",
                            Price = 889m
                        },
                        new
                        {
                            ProductId = 68,
                            Descripcion = "Description for product 68",
                            Name = "Product68",
                            Price = 859m
                        },
                        new
                        {
                            ProductId = 69,
                            Descripcion = "Description for product 69",
                            Name = "Product69",
                            Price = 604m
                        },
                        new
                        {
                            ProductId = 70,
                            Descripcion = "Description for product 70",
                            Name = "Product70",
                            Price = 380m
                        },
                        new
                        {
                            ProductId = 71,
                            Descripcion = "Description for product 71",
                            Name = "Product71",
                            Price = 289m
                        },
                        new
                        {
                            ProductId = 72,
                            Descripcion = "Description for product 72",
                            Name = "Product72",
                            Price = 502m
                        },
                        new
                        {
                            ProductId = 73,
                            Descripcion = "Description for product 73",
                            Name = "Product73",
                            Price = 798m
                        },
                        new
                        {
                            ProductId = 74,
                            Descripcion = "Description for product 74",
                            Name = "Product74",
                            Price = 666m
                        },
                        new
                        {
                            ProductId = 75,
                            Descripcion = "Description for product 75",
                            Name = "Product75",
                            Price = 581m
                        },
                        new
                        {
                            ProductId = 76,
                            Descripcion = "Description for product 76",
                            Name = "Product76",
                            Price = 304m
                        },
                        new
                        {
                            ProductId = 77,
                            Descripcion = "Description for product 77",
                            Name = "Product77",
                            Price = 827m
                        },
                        new
                        {
                            ProductId = 78,
                            Descripcion = "Description for product 78",
                            Name = "Product78",
                            Price = 929m
                        },
                        new
                        {
                            ProductId = 79,
                            Descripcion = "Description for product 79",
                            Name = "Product79",
                            Price = 481m
                        },
                        new
                        {
                            ProductId = 80,
                            Descripcion = "Description for product 80",
                            Name = "Product80",
                            Price = 208m
                        },
                        new
                        {
                            ProductId = 81,
                            Descripcion = "Description for product 81",
                            Name = "Product81",
                            Price = 963m
                        },
                        new
                        {
                            ProductId = 82,
                            Descripcion = "Description for product 82",
                            Name = "Product82",
                            Price = 445m
                        },
                        new
                        {
                            ProductId = 83,
                            Descripcion = "Description for product 83",
                            Name = "Product83",
                            Price = 396m
                        },
                        new
                        {
                            ProductId = 84,
                            Descripcion = "Description for product 84",
                            Name = "Product84",
                            Price = 500m
                        },
                        new
                        {
                            ProductId = 85,
                            Descripcion = "Description for product 85",
                            Name = "Product85",
                            Price = 156m
                        },
                        new
                        {
                            ProductId = 86,
                            Descripcion = "Description for product 86",
                            Name = "Product86",
                            Price = 155m
                        },
                        new
                        {
                            ProductId = 87,
                            Descripcion = "Description for product 87",
                            Name = "Product87",
                            Price = 412m
                        },
                        new
                        {
                            ProductId = 88,
                            Descripcion = "Description for product 88",
                            Name = "Product88",
                            Price = 100m
                        },
                        new
                        {
                            ProductId = 89,
                            Descripcion = "Description for product 89",
                            Name = "Product89",
                            Price = 778m
                        },
                        new
                        {
                            ProductId = 90,
                            Descripcion = "Description for product 90",
                            Name = "Product90",
                            Price = 879m
                        },
                        new
                        {
                            ProductId = 91,
                            Descripcion = "Description for product 91",
                            Name = "Product91",
                            Price = 397m
                        },
                        new
                        {
                            ProductId = 92,
                            Descripcion = "Description for product 92",
                            Name = "Product92",
                            Price = 865m
                        },
                        new
                        {
                            ProductId = 93,
                            Descripcion = "Description for product 93",
                            Name = "Product93",
                            Price = 392m
                        },
                        new
                        {
                            ProductId = 94,
                            Descripcion = "Description for product 94",
                            Name = "Product94",
                            Price = 758m
                        },
                        new
                        {
                            ProductId = 95,
                            Descripcion = "Description for product 95",
                            Name = "Product95",
                            Price = 179m
                        },
                        new
                        {
                            ProductId = 96,
                            Descripcion = "Description for product 96",
                            Name = "Product96",
                            Price = 430m
                        },
                        new
                        {
                            ProductId = 97,
                            Descripcion = "Description for product 97",
                            Name = "Product97",
                            Price = 949m
                        },
                        new
                        {
                            ProductId = 98,
                            Descripcion = "Description for product 98",
                            Name = "Product98",
                            Price = 146m
                        },
                        new
                        {
                            ProductId = 99,
                            Descripcion = "Description for product 99",
                            Name = "Product99",
                            Price = 316m
                        },
                        new
                        {
                            ProductId = 100,
                            Descripcion = "Description for product 100",
                            Name = "Product100",
                            Price = 877m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("ProductInStockId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 78
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 1,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 1,
                            Stock = 44
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 1,
                            Stock = 25
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 1,
                            Stock = 85
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 1,
                            Stock = 51
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 1,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 1,
                            Stock = 84
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 1,
                            Stock = 84
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 1,
                            Stock = 31
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 1,
                            Stock = 65
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 1,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 1,
                            Stock = 43
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 1,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 1,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 1,
                            Stock = 28
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 1,
                            Stock = 33
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 1,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 1,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 1,
                            Stock = 21
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 1,
                            Stock = 98
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 1,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 1,
                            Stock = 31
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 1,
                            Stock = 77
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 1,
                            Stock = 33
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 1,
                            Stock = 27
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 1,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 1,
                            Stock = 81
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 1,
                            Stock = 32
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 1,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 1,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 1,
                            Stock = 68
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 1,
                            Stock = 96
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 1,
                            Stock = 64
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 1,
                            Stock = 30
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 1,
                            Stock = 85
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 1,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 1,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 1,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 1,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 1,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 1,
                            Stock = 50
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 1,
                            Stock = 32
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 1,
                            Stock = 28
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 1,
                            Stock = 83
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 1,
                            Stock = 77
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 1,
                            Stock = 34
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 1,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 1,
                            Stock = 24
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 1,
                            Stock = 37
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 1,
                            Stock = 68
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 1,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 1,
                            Stock = 86
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 1,
                            Stock = 86
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 1,
                            Stock = 43
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 1,
                            Stock = 66
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 1,
                            Stock = 79
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 1,
                            Stock = 67
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 1,
                            Stock = 91
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 1,
                            Stock = 58
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 1,
                            Stock = 36
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 1,
                            Stock = 23
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 1,
                            Stock = 52
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 1,
                            Stock = 82
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 1,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 1,
                            Stock = 96
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 1,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 1,
                            Stock = 78
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 1,
                            Stock = 75
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 1,
                            Stock = 83
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 1,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 1,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 1,
                            Stock = 96
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 1,
                            Stock = 96
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 1,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 1,
                            Stock = 47
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 1,
                            Stock = 79
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 1,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 1,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 1,
                            Stock = 56
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 1,
                            Stock = 92
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 1,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 1,
                            Stock = 56
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 1,
                            Stock = 94
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 1,
                            Stock = 33
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 1,
                            Stock = 92
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 1,
                            Stock = 82
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 1,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 1,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 1,
                            Stock = 64
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 1,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 1,
                            Stock = 42
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 1,
                            Stock = 27
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 1,
                            Stock = 45
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 1,
                            Stock = 72
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 1,
                            Stock = 96
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 1,
                            Stock = 98
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 1,
                            Stock = 50
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 1,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 1,
                            Stock = 87
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
